// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qWNgvStGeF1Ule9WojAo2_RiM9Pzf7k',
    appId: '1:234142976479:web:91450ab62d06ada2359c6a',
    messagingSenderId: '234142976479',
    projectId: 'serveasy-41bd3',
    authDomain: 'serveasy-41bd3.firebaseapp.com',
    storageBucket: 'serveasy-41bd3.firebasestorage.app',
    measurementId: 'G-TFL9LQ376R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp4OUR37dHgKPgZ0-Xi7Y89KKeSfbW2a0',
    appId: '1:234142976479:android:d41067d447eb21f4359c6a',
    messagingSenderId: '234142976479',
    projectId: 'serveasy-41bd3',
    storageBucket: 'serveasy-41bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV052WShgqKmx37TA3rx5eA6pDrsemfq0',
    appId: '1:234142976479:ios:211f71d117a98225359c6a',
    messagingSenderId: '234142976479',
    projectId: 'serveasy-41bd3',
    storageBucket: 'serveasy-41bd3.firebasestorage.app',
    iosBundleId: 'com.example.socialProject',
  );
}
